### ISSUE TITLE
Deprecation warning shown: Warning: The 'set-output command is deprecated

### ISSUE THREAD

**Issue by weyert** [endorama/asdf-parse-tool-versions#247]
When you use this Github Action it shows the following deprecation message:
> Warning: The 'set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by endorama** [comment]
Hello, thank you for reporting this. Happy to receive a contribution for it, or I'll work on a fix in the next weeks.

**Comment by weyert** [comment]
I have raised a PR that updates the dependencies and sets  Node to v20. I think that should fix it. 
Let me know, if you prefer separate PRs for the different changes

**Comment by endorama** [comment]
Thanks a lot for the PR

The CI is failing but I should be able to address it tomorrow.

**Comment by weyert** [comment]
Thanks @endorama. I am not sure what the failing workflow meant. Not seeing what causing the issue to be honest

**Comment by weyert** [comment]
@endorama Do you know how I can fix the failing workflow?
